let state = {
    lead: {
        add_date: null,
        carrier_operation: null,
        comment: null,
        created_at: null,
        dba_name: null,
        description: null,
        dot_number: '555',
        driver_total: null,
        email_address: null,
        fax: null,
        hm_flag: null,
        id: null,
        last_insurance_carrier: null,
        last_insurance_date: null,
        insurance_cancellation_date: null,
        legal_name: null,
        mailing_city: null,
        mailing_country: null,
        mailing_state: null,
        mailing_street: null,
        mailing_zip: null,
        mcs150_date: null,
        mcs150_mileage: null,
        mcs150_mileage_year: null,
        nbr_power_unit: null,
        oic_state: null,
        pc_flag: null,
        person_name: null,
        phy_city: null,
        phy_country: null,
        phy_state: null,
        phy_street: null,
        phy_zip: null,
        telephone: null,
        updated_at: null,        
    },
    isLoading: false,
    errors: {}
}

export default state